# Generated by Django 5.0.6 on 2024-07-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="selected_option",
            field=models.CharField(default="default_value", max_length=50),
        ),
        migrations.AddField(
            model_name="files",
            name="target",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
