# Generated by Django 5.0.6 on 2024-07-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_files_selected_option_files_target"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="files",
            name="selected_option",
        ),
        migrations.AddField(
            model_name="files",
            name="selectedOption",
            field=models.CharField(default="", max_length=50),
        ),
    ]
